from tts_api.main import create_app


def test_original_doubao_api_surface_is_preserved():
    routes = {
        (method, route.path)
        for route in create_app().routes
        for method in getattr(route, "methods", set())
    }
    expected = {
        ("GET", "/api/announcements"),
        ("GET", "/api/force-update"),
        ("GET", "/api/service-status"),
        ("POST", "/api/tts"),
        ("POST", "/api/"),
        ("POST", "/tts/tts"),
        ("POST", "/tts/"),
        ("GET", "/tts/health"),
        ("DELETE", "/audio/{filename}"),
        ("DELETE", "/api/audio/{filename}"),
        ("GET", "/api/voices"),
        ("GET", "/api/voices/search"),
        ("GET", "/api/console/status"),
        ("GET", "/api/console/cookies"),
        ("GET", "/api/console/health"),
        ("GET", "/api/console/cache-stats"),
        ("GET", "/api/console/clean-cache"),
        ("GET", "/api/cookies"),
        ("GET", "/api/cookies/stats"),
        ("POST", "/api/cookies/rotation-config"),
        ("PUT", "/api/cookies/{cookie_id}/usage-limit"),
        ("GET", "/api/cookies/{cookie_id}"),
        ("POST", "/api/cookies"),
        ("PUT", "/api/cookies/{cookie_id}"),
        ("DELETE", "/api/cookies/{cookie_id}"),
        ("POST", "/api/cookies/rotate"),
        ("POST", "/api/cookies/{cookie_id}/test"),
        ("POST", "/api/cookies/{cookie_id}/toggle"),
        ("POST", "/api/cookies/batch/test"),
        ("DELETE", "/api/cookies"),
        ("POST", "/api/auth/qr-code"),
        ("POST", "/api/auth/qr-status"),
        ("POST", "/api/auth/qr-confirm"),
        ("GET", "/api/auth/qr-sessions"),
        ("GET", "/api/docs"),
        ("GET", "/api/docs/{document_id}"),
        ("POST", "/api/docs/refresh"),
        ("GET", "/api/docs/search"),
        ("GET", "/api/settings"),
        ("POST", "/api/settings"),
        ("PUT", "/api/settings/item"),
        ("GET", "/api/settings/item"),
        ("POST", "/api/settings/reset"),
        ("GET", "/api/settings/device-id"),
        ("POST", "/api/settings/device-id/regenerate"),
        ("POST", "/api/settings/device-id/auto-generate"),
        ("POST", "/api/settings/update"),
        ("GET", "/api/legado/tts-config"),
        ("GET", "/api/legado/tts-config-prefab"),
        ("GET", "/api/reader/tts/stream"),
        ("GET", "/api/reader/tts/stream-prefetch"),
        ("POST", "/api/legado/proxy/bookshelf"),
        ("POST", "/api/legado/proxy/chapters"),
        ("POST", "/api/legado/proxy/content"),
        ("GET", "/api/legado/proxy/cover"),
        ("POST", "/api/legado/prefetch/start"),
        ("POST", "/api/legado/prefetch/batch-start"),
        ("GET", "/api/legado/prefetch/status/{task_id}"),
        ("POST", "/api/legado/prefetch/pause/{task_id}"),
        ("POST", "/api/legado/prefetch/resume/{task_id}"),
        ("POST", "/api/legado/prefetch/cancel/{task_id}"),
        ("DELETE", "/api/legado/prefetch/files/{task_id}"),
        ("POST", "/api/legado/prefetch/retry/{task_id}"),
        ("GET", "/api/legado/prefetch/tasks"),
        ("DELETE", "/api/legado/prefetch/tasks/{task_id}"),
        ("DELETE", "/api/legado/prefetch/book/{book_id}"),
        ("GET", "/api/legado/prefetch/cache/{book_id}/{chapter_id}"),
        ("POST", "/api/legado/prefetch/chapters-status/{book_id}"),
        ("DELETE", "/api/legado/prefetch/chapter/{book_id}/{chapter_id}"),
        ("GET", "/api/legado/prefetch/audio"),
        ("POST", "/api/legado/book-cache/start"),
        ("GET", "/api/legado/book-cache/progress"),
        ("POST", "/api/legado/book-cache/clear-progress"),
        ("POST", "/api/legado/book-cache/cancel"),
        ("GET", "/api/legado/book-cache/status"),
        ("GET", "/api/legado/book-cache/list"),
        ("GET", "/api/legado/book-cache/cover/{book_id}"),
        ("GET", "/api/legado/book-cache/chapters"),
        ("DELETE", "/api/legado/book-cache/delete"),
        ("GET", "/api/legado/book-id/generate"),
        ("DELETE", "/api/legado/book-cache/clear"),
        ("GET", "/api/legado/book-cache/stats"),
        ("GET", "/api/legado/book-cache/chapter"),
    }

    assert expected <= routes
